

# 50 văn bản tự nhiên
natural_texts = [
    "The quick brown fox jumps over the lazy dog",
    "Machine learning is powerful and fun",
    "Natural language processing helps computers understand human language",
    "Artificial intelligence is transforming industries",
    "Data science combines statistics and programming",
    "Reading books expands knowledge and imagination",
    "The sun rises in the east and sets in the west",
    "Music is a universal language",
    "Rainbows appear after rain when sunlight reflects",
    "He went to the market to buy fresh vegetables",
    "Education is the key to success",
    "Traveling opens your mind to new cultures",
    "He reads the newspaper every morning",
    "The garden is full of beautiful flowers",
    "She enjoys painting landscapes during weekends",
    "Honesty is the best policy",
    "The children are playing in the park",
    "Birds fly high in the sky",
    "Winter is colder than summer",
    "A healthy diet improves well-being",
    "Libraries are quiet places to study",
    "He always drinks coffee in the morning",
    "Technology evolves rapidly",
    "She is writing a new novel",
    "This cake tastes delicious",
    "The river flows gently through the valley",
    "We watched a documentary on space",
    "Students must complete their homework on time",
    "The city was silent at night",
    "There are many stars in the galaxy",
    "They planted trees along the roadside",
    "Her handwriting is neat and elegant",
    "The plane landed safely at the airport",
    "He enjoys jogging in the early morning",
    "Reading helps develop vocabulary",
    "The artist displayed her paintings at the gallery",
    "He fixed the broken chair with glue",
    "People gathered to celebrate the festival",
    "The train arrived five minutes late",
    "Sunlight provides vitamin D",
    "My dog loves to chase butterflies",
    "The baby smiled at her mother",
    "She wore a blue dress to the party",
    "Cooking at home is healthier and cheaper",
    "The scientist conducted several experiments",
    "The moon glowed brightly in the night sky",
    "Children must be taught kindness and empathy",
    "He listened to classical music while studying",
    "A good sleep schedule improves focus",
    "They walked through the forest trail"
]

# 50 văn bản giấu tin
stego_texts = [
    "This    is  a   secret    message",
    "Hello  world  this   is    stego   text",
    "Hiding   info     in   spaces",
    "This  sentence  is    not   normal",
    "Every   space   hides something",
    "Too    many  spaces    here",
    "This  is     an   embedded    message",
    "Notice  the     gaps  in  spacing",
    "Why     is  this   text   so    weird",
    "A  message    may     be   here",
    "Double   space   can   be  a   sign",
    "Extra   gaps    are    suspicious",
    "H e l l o   w o r l d",
    "White   space    steganography",
    "Hidden      in     plain    sight",
    "The   fox    hides     info",
    "Text      may     contain     secrets",
    "Every     extra     space     matters",
    "Some    letters     are    hidden",
    "T  h  i  s     t  e  x  t     i  s     s  u  s",
    "This   is  not   what   it   seems",
    "Hidden     message    inside    text",
    "Find     the     anomaly",
    "Spacing     is     everything",
    "Look   closer     at    the     structure",
    "This      could     be     nothing",
    "Maybe      it's     something",
    "Odd     formatting     detected",
    "Spacing    game    is    on",
    "Not     your     average     sentence",
    "Does     this     look     normal",
    "Suspect     the     unusual     spaces",
    "Observe     the     weirdness",
    "This     is     not     obvious",
    "Everything     is     deliberate",
    "Find      the      oddity",
    "Structured      noise      detected",
    "Maybe      there's      a      key",
    "Invisible     ink     between     words",
    "Can     you     see     the     pattern",
    "Message      within      message",
    "Spaces     tell     the     truth",
    "Looks     natural     but     isn't",
    "Spot      the      difference",
    "Patterns      in     punctuation",
    "Subtle      spacing      clues",
    "Encryption      through      space",
    "Hidden      trail      of      blanks",
    "A      spacey      message",
    "Hacked       text       revealed"
]
# Gộp và tạo nhãn
texts = natural_texts + stego_texts
labels = [0] * len(natural_texts) + [1] * len(stego_texts)
